import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
const root=process.cwd();
const read=p=>fs.readFileSync(path.join(root,p),"utf8");
const fn=read("src/features/admin/services/admin.functions.ts");
const server=read("src/features/admin/services/admin.server.ts");
const hook=read("src/features/admin/hooks/useAdmin.ts");
const migration=read("supabase/migrations/20260923233913_fe47f5d2-14a4-4615-a318-cfa84b80b12b.sql");
assert.match(fn,/finance\.adjustment\.create/);
assert.match(fn,/finance\.adjustment\.approve/);
assert.match(fn,/create_funding_request/);
assert.match(fn,/decide_funding_request/);
assert.match(fn,/INVALID_IDEMPOTENCY_KEY/);
assert.match(server,/requireAdminPermission/);
assert.match(hook,/ADMIN_FUNDING_KEY/);
assert.match(migration,/CREATE TABLE public\.funding_requests/);
assert.match(migration,/idempotency_key uuid NOT NULL UNIQUE/);
assert.match(migration,/maker_user_id uuid NOT NULL/);
assert.match(migration,/checker_user_id uuid/);
assert.match(migration,/ledger_transaction_id uuid UNIQUE/);
assert.match(migration,/IF _request\.maker_user_id = auth\.uid\(\) THEN RAISE EXCEPTION 'four-eyes approval required'/);
assert.match(migration,/post_ledger_transaction/);
assert.match(migration,/funding:'.*request/);
assert.match(migration,/REVOKE ALL ON FUNCTION public\.create_funding_request/);
assert.match(migration,/REVOKE ALL ON FUNCTION public\.decide_funding_request/);
assert.match(migration,/admin_audit_events/);
console.log("STEP 07 STATIC CERTIFICATION: PASS");
console.log("Covered: permission separation, authenticated server commands, strict validation, UUID idempotency, maker-checker enforcement, double-entry posting, immutable ledger transaction linkage, RLS read restriction, function privilege revocation, and audit events.");
