import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const sql=readFileSync("supabase/migrations/20261002120000_step10_kyc_notifications.sql","utf8");
assert.match(sql,/service_review_identity_application/);
assert.match(sql,/kyc\.info_required:/);
assert.match(sql,/service_decide_identity_application/);
assert.match(sql,/kyc\.verified:/);
assert.match(sql,/kyc\.rejected:/);
assert.match(sql,/kyc\.review_returned:/);
assert.match(sql,/emit_customer_notification\(/);
assert.match(sql,/has_permission\(_actor_user_id,'kyc\.review'\)/);
assert.match(sql,/has_permission\(_actor_user_id,'kyc\.approve'\)/);
console.log("Step 10 KYC notifications certification: PASS");