/** Predefined onboarding choices so customers pick instead of typing. Values stay stable (English); labels are localised. */
export type Choice = { value: string; fr: string; en: string };

export const COUNTRIES: Choice[] = [
  { value: "Algeria", fr: "Algérie", en: "Algeria" },
  { value: "Angola", fr: "Angola", en: "Angola" },
  { value: "Benin", fr: "Bénin", en: "Benin" },
  { value: "Botswana", fr: "Botswana", en: "Botswana" },
  { value: "Burkina Faso", fr: "Burkina Faso", en: "Burkina Faso" },
  { value: "Burundi", fr: "Burundi", en: "Burundi" },
  { value: "Cabo Verde", fr: "Cap-Vert", en: "Cabo Verde" },
  { value: "Cameroon", fr: "Cameroun", en: "Cameroon" },
  { value: "Central African Republic", fr: "République centrafricaine", en: "Central African Republic" },
  { value: "Chad", fr: "Tchad", en: "Chad" },
  { value: "Comoros", fr: "Comores", en: "Comoros" },
  { value: "Democratic Republic of the Congo", fr: "République démocratique du Congo", en: "Democratic Republic of the Congo" },
  { value: "Republic of the Congo", fr: "République du Congo", en: "Republic of the Congo" },
  { value: "Côte d'Ivoire", fr: "Côte d'Ivoire", en: "Côte d'Ivoire" },
  { value: "Djibouti", fr: "Djibouti", en: "Djibouti" },
  { value: "Egypt", fr: "Égypte", en: "Egypt" },
  { value: "Equatorial Guinea", fr: "Guinée équatoriale", en: "Equatorial Guinea" },
  { value: "Eritrea", fr: "Érythrée", en: "Eritrea" },
  { value: "Eswatini", fr: "Eswatini", en: "Eswatini" },
  { value: "Ethiopia", fr: "Éthiopie", en: "Ethiopia" },
  { value: "Gabon", fr: "Gabon", en: "Gabon" },
  { value: "Gambia", fr: "Gambie", en: "Gambia" },
  { value: "Ghana", fr: "Ghana", en: "Ghana" },
  { value: "Guinea", fr: "Guinée", en: "Guinea" },
  { value: "Guinea-Bissau", fr: "Guinée-Bissau", en: "Guinea-Bissau" },
  { value: "Kenya", fr: "Kenya", en: "Kenya" },
  { value: "Lesotho", fr: "Lesotho", en: "Lesotho" },
  { value: "Liberia", fr: "Libéria", en: "Liberia" },
  { value: "Libya", fr: "Libye", en: "Libya" },
  { value: "Madagascar", fr: "Madagascar", en: "Madagascar" },
  { value: "Malawi", fr: "Malawi", en: "Malawi" },
  { value: "Mali", fr: "Mali", en: "Mali" },
  { value: "Mauritania", fr: "Mauritanie", en: "Mauritania" },
  { value: "Mauritius", fr: "Maurice", en: "Mauritius" },
  { value: "Morocco", fr: "Maroc", en: "Morocco" },
  { value: "Mozambique", fr: "Mozambique", en: "Mozambique" },
  { value: "Namibia", fr: "Namibie", en: "Namibia" },
  { value: "Niger", fr: "Niger", en: "Niger" },
  { value: "Nigeria", fr: "Nigeria", en: "Nigeria" },
  { value: "Rwanda", fr: "Rwanda", en: "Rwanda" },
  { value: "Sao Tome and Principe", fr: "Sao Tomé-et-Principe", en: "Sao Tome and Principe" },
  { value: "Senegal", fr: "Sénégal", en: "Senegal" },
  { value: "Seychelles", fr: "Seychelles", en: "Seychelles" },
  { value: "Sierra Leone", fr: "Sierra Leone", en: "Sierra Leone" },
  { value: "Somalia", fr: "Somalie", en: "Somalia" },
  { value: "South Africa", fr: "Afrique du Sud", en: "South Africa" },
  { value: "South Sudan", fr: "Soudan du Sud", en: "South Sudan" },
  { value: "Sudan", fr: "Soudan", en: "Sudan" },
  { value: "Tanzania", fr: "Tanzanie", en: "Tanzania" },
  { value: "Togo", fr: "Togo", en: "Togo" },
  { value: "Tunisia", fr: "Tunisie", en: "Tunisia" },
  { value: "Uganda", fr: "Ouganda", en: "Uganda" },
  { value: "Zambia", fr: "Zambie", en: "Zambia" },
  { value: "Zimbabwe", fr: "Zimbabwe", en: "Zimbabwe" },
  { value: "Trinidad and Tobago", fr: "Trinité-et-Tobago", en: "Trinidad and Tobago" },
  { value: "Barbados", fr: "Barbade", en: "Barbados" },
  { value: "Jamaica", fr: "Jamaïque", en: "Jamaica" },
  { value: "Grenada", fr: "Grenade", en: "Grenada" },
  { value: "Saint Lucia", fr: "Sainte-Lucie", en: "Saint Lucia" },
  { value: "Saint Vincent and the Grenadines", fr: "Saint-Vincent-et-les-Grenadines", en: "Saint Vincent and the Grenadines" },
  { value: "Guyana", fr: "Guyana", en: "Guyana" },
  { value: "Suriname", fr: "Suriname", en: "Suriname" },
  { value: "Bahamas", fr: "Bahamas", en: "Bahamas" },
  { value: "Antigua and Barbuda", fr: "Antigua-et-Barbuda", en: "Antigua and Barbuda" },
  { value: "Dominica", fr: "Dominique", en: "Dominica" },
  { value: "Venezuela", fr: "Venezuela", en: "Venezuela" },
  { value: "United States", fr: "États-Unis", en: "United States" },
  { value: "Canada", fr: "Canada", en: "Canada" },
  { value: "United Kingdom", fr: "Royaume-Uni", en: "United Kingdom" },
  { value: "France", fr: "France", en: "France" },
  { value: "Belgium", fr: "Belgique", en: "Belgium" },
  { value: "Switzerland", fr: "Suisse", en: "Switzerland" },
  { value: "Germany", fr: "Allemagne", en: "Germany" },
  { value: "Spain", fr: "Espagne", en: "Spain" },
  { value: "Italy", fr: "Italie", en: "Italy" },
  { value: "Netherlands", fr: "Pays-Bas", en: "Netherlands" },
  { value: "Portugal", fr: "Portugal", en: "Portugal" },
  { value: "Brazil", fr: "Brésil", en: "Brazil" },
  { value: "Mexico", fr: "Mexique", en: "Mexico" },
  { value: "Colombia", fr: "Colombie", en: "Colombia" },
  { value: "India", fr: "Inde", en: "India" },
  { value: "China", fr: "Chine", en: "China" },
  { value: "Japan", fr: "Japon", en: "Japan" },
  { value: "United Arab Emirates", fr: "Émirats arabes unis", en: "United Arab Emirates" },
  { value: "Australia", fr: "Australie", en: "Australia" },
];

export const OCCUPATIONS: Choice[] = [
  { value: "Employee", fr: "Salarié(e)", en: "Employee" },
  { value: "Civil servant", fr: "Fonctionnaire", en: "Civil servant" },
  { value: "Self-employed", fr: "Indépendant(e) / entrepreneur", en: "Self-employed / entrepreneur" },
  { value: "Company director", fr: "Dirigeant(e) d'entreprise", en: "Company director" },
  { value: "Liberal profession", fr: "Profession libérale", en: "Liberal profession" },
  { value: "Health professional", fr: "Professionnel(le) de santé", en: "Health professional" },
  { value: "Teacher", fr: "Enseignant(e)", en: "Teacher" },
  { value: "Engineer / IT", fr: "Ingénieur(e) / informatique", en: "Engineer / IT" },
  { value: "Energy sector", fr: "Secteur énergie", en: "Energy sector" },
  { value: "Tourism / hospitality", fr: "Tourisme / hôtellerie", en: "Tourism / hospitality" },
  { value: "Student", fr: "Étudiant(e)", en: "Student" },
  { value: "Retired", fr: "Retraité(e)", en: "Retired" },
  { value: "Unemployed", fr: "Sans emploi", en: "Unemployed" },
];

/** Trinidad and Tobago municipal corporations + Tobago. */
export const TT_REGIONS = [
  "Port of Spain", "San Fernando", "Arima", "Chaguanas", "Point Fortin",
  "Diego Martin", "San Juan–Laventille", "Tunapuna–Piarco", "Sangre Grande",
  "Couva–Tabaquite–Talparo", "Mayaro–Rio Claro", "Princes Town", "Penal–Debe",
  "Siparia", "Tobago",
];

export const TT_CITIES = [
  "Port of Spain", "Woodbrook", "St. James", "Maraval", "Diego Martin", "San Fernando",
  "Chaguanas", "Arima", "Couva", "Point Fortin", "Tunapuna", "St. Augustine", "Sangre Grande",
  "Princes Town", "Siparia", "Scarborough", "Crown Point", "Plymouth", "Roxborough",
];

export function choiceLabel(list: Choice[], value: string | null | undefined, en: boolean): string {
  const item = list.find((c) => c.value === value);
  return item ? (en ? item.en : item.fr) : (value ?? "");
}
