/** English editorial copy for the homepage; the French source remains unchanged. */
export const HOME_EN = {
  date: "Trinidad and Tobago · since 1972",
  intro: "Rooted in Woodbrook. Built around your plans today.",
  lead: "Founded on July 23, 1972 in Trinidad and Tobago. Check your US dollar account and track transfers in your customer account.",
  open: "Open an account", history: "Our story",
  historyEyebrow: "Our story in brief", historyTitle: "Here in Trinidad and Tobago since 1972.",
  historyDescription: "Our identity and official contact details, without invented claims.", historyLink: "Discover the bank",
  facts: ["Founded", "Head office", "Supervision", "SWIFT / BIC"],
  regional: "Around the region", newsTitle: "Financial news from Trinidad and Tobago",
  newsDescription: "Dated releases from the Central Bank of Trinidad and Tobago. Read the original announcements.",
  centralBank: "Central Bank", placesEyebrow: "At home", placesTitle: "Rooted in Trinidad and Tobago",
  placesDescription: "From Port of Spain to the north coast, the places around our home.",
  daily: "Everyday banking", accountTitle: "Your account, made simple",
  security: "Security", securityTitle: "Your account is protected at every step", securityLink: "Explore security",
  onboarding: "Opening an account", onboardingTitle: "Five steps, entirely online",
  faq: "Frequently asked questions", faqTitle: "Answers to common questions", faqLink: "Help centre",
  benefits: [
    ["See your money clearly", "Available balance, recent activity and pending transactions in one place."],
    ["Simple transfers", "Choose a beneficiary, enter an amount and confirm. Every step is explained."],
    ["Stay in control", "Review your history, filter by date or status, and receive alerts for important activity."],
    ["Security by design", "Strong authentication, session controls and confirmation of sensitive actions."],
  ],
  highlights: [
    ["Stronger authentication", "An extra check protects your sign-in and sensitive actions."],
    ["Manage your sessions", "Review active sessions and close any you don't recognize."],
    ["Confirm transactions", "Transfers and sensitive changes require explicit confirmation."],
    ["Activity alerts", "Get updates about important account activity."],
  ],
  steps: [
    ["Create your profile", "Name, email address and password."],
    ["Confirm your details", "Verify your email and phone number."],
    ["Provide required information", "Information needed to open your account."],
    ["Verify your identity", "Submit an identity document online."],
    ["Access your account", "Your account opens once your application is approved."],
  ],
  faqs: [
    ["How do I open an account?", "Apply online: create a profile, confirm your contact details, provide the required information and verify your identity. Your account opens after approval."],
    ["How do I access my account?", "Sign in with your email address and password. An additional check may be required."],
    ["How do I make a transfer?", "In your account, choose a beneficiary, enter an amount, review the details and confirm."],
    ["Where can I find my statements?", "In the Statements section of your account, where you can view and download PDFs."],
    ["What happens if extra verification is needed?", "The app shows why, which documents are required and the review status."],
    ["How can I contact the bank?", "Customers can use secure messaging in their account. Visitors can use the public contact form."],
  ],
  news: [
    ["Towards a regional CARICOM payments system", "Regional central banks are advancing discussions on CAPSS, a platform for instant local-currency payments between member states."],
    ["Virtual assets: opportunities and risks", "A central bank discussion on virtual asset service providers at the 2026 Research Review Seminar."],
    ["Operating in a Fractured World", "The opening of the central bank's annual research seminar on economic resilience, innovation and sustainability."],
    ["New registered payment service provider", "The central bank expands GraceKennedy (Trinidad & Tobago) Limited's registration as a payment service provider."],
  ],
} as const;