/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppBeneficiariesRouteImport } from './routes/app.beneficiaries'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppMoreRouteImport } from './routes/app.more'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppSecurityRouteImport } from './routes/app.security'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppStatementsRouteImport } from './routes/app.statements'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DevDesignSystemRouteImport } from './routes/dev.design-system'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingAddressRouteImport } from './routes/onboarding.address'
import { Route as OnboardingDocumentsRouteImport } from './routes/onboarding.documents'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding.profile'
import { Route as OnboardingReviewRouteImport } from './routes/onboarding.review'
import { Route as OnboardingStatusRouteImport } from './routes/onboarding.status'
import { Route as AppAccountsIndexRouteImport } from './routes/app.accounts.index'
import { Route as AppTransfersIndexRouteImport } from './routes/app.transfers.index'
import { Route as AppTransfersNewRouteImport } from './routes/app.transfers.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppBeneficiariesRoute = AppBeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementsRoute = AppStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDesignSystemRoute = DevDesignSystemRouteImport.update({
  id: '/dev/design-system',
  path: '/dev/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAddressRoute = OnboardingAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingDocumentsRoute = OnboardingDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingReviewRoute = OnboardingReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStatusRoute = OnboardingStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppTransfersIndexRoute = AppTransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersNewRoute = AppTransfersNewRouteImport.update({
  id: '/transfers/new',
  path: '/transfers/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/session-expired': typeof SessionExpiredRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/app/accounts': typeof AppAccountsRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/beneficiaries': typeof AppBeneficiariesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/more': typeof AppMoreRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/security': typeof AppSecurityRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/statements': typeof AppStatementsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/onboarding/address': typeof OnboardingAddressRoute
  '/onboarding/documents': typeof OnboardingDocumentsRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/onboarding/status': typeof OnboardingStatusRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/app/transfers/new': typeof AppTransfersNewRoute
  '/app/accounts/': typeof AppAccountsIndexRoute
  '/app/transfers/': typeof AppTransfersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/session-expired': typeof SessionExpiredRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/app/activity': typeof AppActivityRoute
  '/app/beneficiaries': typeof AppBeneficiariesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/more': typeof AppMoreRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/security': typeof AppSecurityRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/statements': typeof AppStatementsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/onboarding/address': typeof OnboardingAddressRoute
  '/onboarding/documents': typeof OnboardingDocumentsRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/onboarding/status': typeof OnboardingStatusRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/app/transfers/new': typeof AppTransfersNewRoute
  '/app/accounts': typeof AppAccountsIndexRoute
  '/app/transfers': typeof AppTransfersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/session-expired': typeof SessionExpiredRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/app/accounts': typeof AppAccountsRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/beneficiaries': typeof AppBeneficiariesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/more': typeof AppMoreRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/security': typeof AppSecurityRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/statements': typeof AppStatementsRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/onboarding/address': typeof OnboardingAddressRoute
  '/onboarding/documents': typeof OnboardingDocumentsRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/onboarding/status': typeof OnboardingStatusRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/app/transfers/new': typeof AppTransfersNewRoute
  '/app/accounts/': typeof AppAccountsIndexRoute
  '/app/transfers/': typeof AppTransfersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accounts'
    | '/admin'
    | '/app'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/help'
    | '/legal'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/security'
    | '/session-expired'
    | '/terms'
    | '/verify-email'
    | '/admin/dashboard'
    | '/app/accounts'
    | '/app/activity'
    | '/app/beneficiaries'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/messages'
    | '/app/more'
    | '/app/notifications'
    | '/app/profile'
    | '/app/security'
    | '/app/settings'
    | '/app/statements'
    | '/app/transactions'
    | '/auth/callback'
    | '/dev/design-system'
    | '/onboarding/address'
    | '/onboarding/documents'
    | '/onboarding/profile'
    | '/onboarding/review'
    | '/onboarding/status'
    | '/admin/'
    | '/app/'
    | '/onboarding/'
    | '/app/transfers/new'
    | '/app/accounts/'
    | '/app/transfers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accounts'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/help'
    | '/legal'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/security'
    | '/session-expired'
    | '/terms'
    | '/verify-email'
    | '/admin/dashboard'
    | '/app/activity'
    | '/app/beneficiaries'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/messages'
    | '/app/more'
    | '/app/notifications'
    | '/app/profile'
    | '/app/security'
    | '/app/settings'
    | '/app/statements'
    | '/app/transactions'
    | '/auth/callback'
    | '/dev/design-system'
    | '/onboarding/address'
    | '/onboarding/documents'
    | '/onboarding/profile'
    | '/onboarding/review'
    | '/onboarding/status'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/app/transfers/new'
    | '/app/accounts'
    | '/app/transfers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accounts'
    | '/admin'
    | '/app'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/help'
    | '/legal'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/security'
    | '/session-expired'
    | '/terms'
    | '/verify-email'
    | '/admin/dashboard'
    | '/app/accounts'
    | '/app/activity'
    | '/app/beneficiaries'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/messages'
    | '/app/more'
    | '/app/notifications'
    | '/app/profile'
    | '/app/security'
    | '/app/settings'
    | '/app/statements'
    | '/app/transactions'
    | '/auth/callback'
    | '/dev/design-system'
    | '/onboarding/address'
    | '/onboarding/documents'
    | '/onboarding/profile'
    | '/onboarding/review'
    | '/onboarding/status'
    | '/admin/'
    | '/app/'
    | '/onboarding/'
    | '/app/transfers/new'
    | '/app/accounts/'
    | '/app/transfers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountsRoute: typeof AccountsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DevDesignSystemRoute: typeof DevDesignSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/beneficiaries': {
      id: '/app/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/app/beneficiaries'
      preLoaderRoute: typeof AppBeneficiariesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/more': {
      id: '/app/more'
      path: '/more'
      fullPath: '/app/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/security': {
      id: '/app/security'
      path: '/security'
      fullPath: '/app/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/statements': {
      id: '/app/statements'
      path: '/statements'
      fullPath: '/app/statements'
      preLoaderRoute: typeof AppStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/design-system': {
      id: '/dev/design-system'
      path: '/dev/design-system'
      fullPath: '/dev/design-system'
      preLoaderRoute: typeof DevDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/address': {
      id: '/onboarding/address'
      path: '/address'
      fullPath: '/onboarding/address'
      preLoaderRoute: typeof OnboardingAddressRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/documents': {
      id: '/onboarding/documents'
      path: '/documents'
      fullPath: '/onboarding/documents'
      preLoaderRoute: typeof OnboardingDocumentsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/review': {
      id: '/onboarding/review'
      path: '/review'
      fullPath: '/onboarding/review'
      preLoaderRoute: typeof OnboardingReviewRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/status': {
      id: '/onboarding/status'
      path: '/status'
      fullPath: '/onboarding/status'
      preLoaderRoute: typeof OnboardingStatusRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/app/accounts/': {
      id: '/app/accounts/'
      path: '/'
      fullPath: '/app/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/app/transfers/': {
      id: '/app/transfers/'
      path: '/transfers'
      fullPath: '/app/transfers/'
      preLoaderRoute: typeof AppTransfersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transfers/new': {
      id: '/app/transfers/new'
      path: '/transfers/new'
      fullPath: '/app/transfers/new'
      preLoaderRoute: typeof AppTransfersNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppAccountsRouteChildren {
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
}

const AppAccountsRouteChildren: AppAccountsRouteChildren = {
  AppAccountsIndexRoute: AppAccountsIndexRoute,
}

const AppAccountsRouteWithChildren = AppAccountsRoute._addFileChildren(
  AppAccountsRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRouteWithChildren
  AppActivityRoute: typeof AppActivityRoute
  AppBeneficiariesRoute: typeof AppBeneficiariesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppMoreRoute: typeof AppMoreRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatementsRoute: typeof AppStatementsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTransfersNewRoute: typeof AppTransfersNewRoute
  AppTransfersIndexRoute: typeof AppTransfersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRouteWithChildren,
  AppActivityRoute: AppActivityRoute,
  AppBeneficiariesRoute: AppBeneficiariesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppMoreRoute: AppMoreRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatementsRoute: AppStatementsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppTransfersNewRoute: AppTransfersNewRoute,
  AppTransfersIndexRoute: AppTransfersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingAddressRoute: typeof OnboardingAddressRoute
  OnboardingDocumentsRoute: typeof OnboardingDocumentsRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
  OnboardingReviewRoute: typeof OnboardingReviewRoute
  OnboardingStatusRoute: typeof OnboardingStatusRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingAddressRoute: OnboardingAddressRoute,
  OnboardingDocumentsRoute: OnboardingDocumentsRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
  OnboardingReviewRoute: OnboardingReviewRoute,
  OnboardingStatusRoute: OnboardingStatusRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountsRoute: AccountsRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DevDesignSystemRoute: DevDesignSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
